# Generated by Django 4.2.5 on 2023-09-27 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topics",
            fields=[
                (
                    "title",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Topics_name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=30, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("videos", models.FileField(upload_to="videos/")),
                ("video_preview", models.ImageField(upload_to="video_preview/")),
                (
                    "title",
                    models.CharField(
                        max_length=130, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "topics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="video.topics",
                        verbose_name="Topics",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
