# Generated by Django 4.2.5 on 2023-09-22 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="channels",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="video",
        ),
        migrations.RemoveField(
            model_name="video",
            name="channel",
        ),
        migrations.DeleteModel(
            name="Channel",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
