# Generated by Django 4.2.5 on 2023-09-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0002_remove_userprofile_channels_remove_userprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
